import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import StoreProveider from "../lib/Wrapper/StoreProveider";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: {
    default: "Kshitij Singh",
    template: "%s | Kshitij Singh",
  },

  description:
    "Full-Stack Developer skilled in Next.js, TypeScript, MERN stack, and AI-powered solutions. Explore Kshitij Singh’s projects, experience, and engineering capabilities across modern web development, scalable architectures, and intelligent applications.",

  // Expanded SEO Keywords
  keywords: [
    // Branding & Personal
    "Kshitij Singh",
    "Kshitij Portfolio",
    "Kshitij Full Stack Developer",
    "Kshitij MERN Developer",
    "Kshitij Next.js Developer",
    "Kshitij Singh Developer",
    "indkshitij",
    "Kshitij Software Engineer",
    "Kshitij Web Developer",

    // Job Titles
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Software Engineer",
    "Web Developer",
    "AI Developer",
    "Machine Learning Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "MERN Stack Developer",
    "Full Stack Engineer",
    "Frontend Engineer",
    "Backend Engineer",
    "AI Engineer",
    "Cloud Developer",

    // Core Technologies
    "Next.js",
    "React.js",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "Mongoose",
    "Redux Toolkit",
    "Zustand",
    "Tailwind CSS",
    "HTML5",
    "CSS3",
    "REST API Developer",
    "Web App Developer",
    "Modern Web Development",
    "SSR Developer",
    "ISR Developer",
    "React Query",
    "Framer Motion",
    "Next Auth",
    "JWT Authentication",
    "OAuth Developer",

    // AI & LLM-Related
    "AI Projects",
    "AI Interview Simulator",
    "Generative AI Developer",
    "LLM Developer",
    "Chatbot Developer",
    "OpenAI API Developer",
    "AI-based Web Apps",
    "AI-integrated Applications",
    "AI Automation Developer",
    "AI Model Integration",

    // Performance & Architecture
    "Scalable Web Apps",
    "Microservices Developer",
    "API Developer",
    "Serverless Developer",
    "Vercel Deployment",
    "Cloud Deployment Developer",
    "CI CD Developer",
    "GitHub Actions Developer",
    "Secure Web Development",
    "High Performance Web Apps",
    "Responsive Web Design",
    "SEO Optimized Websites",
    "Mobile Friendly Websites",

    // Coding & Competitive Programming
    "LeetCode Developer",
    "LeetCode India",
    "DSA Developer",
    "Problem Solving Developer",
    "Coding Profile",
    "GitHub Developer",
    "Open Source Developer",
    "GitHub Portfolio",
    "Open Source Contributor",

    // Tools & Platforms
    "Git",
    "GitHub",
    "Vercel",
    "Netlify",
    "Firebase",
    "Docker",
    "Postman",
    "VS Code",
    "Linux Developer",
    "Agile Developer",

    // Portfolio & Branding SEO
    "Developer Portfolio",
    "Portfolio Website",
    "Personal Website Developer",
    "Software Developer Portfolio",
    "Indian Developer Portfolio",
    "JavaScript Projects Portfolio",
    "Full Stack Projects",
    "Frontend Projects",
    "Backend Projects",
    "AI Projects Portfolio",

    // Industry & General Skills
    "Clean Code Developer",
    "UI Developer",
    "UX-aware Developer",
    "Performance Optimization",
    "Best Web Practices Developer",
    "Real World Projects Developer",
    "Coding Enthusiast",
    "Tech Enthusiast",
    "Software Developer India",
    "Next.js India Developer",
    "Full Stack Developer India",
    "React Developer India",
    "MERN Developer India",

    // Social Profiles SEO
    "GitHub indkshitij",
    "LinkedIn Kshitij Singh",
    "LeetCode 1kshitij",
    "Portfolio Kshitij Singh",
    "Instagram kkkshitij",
    "X twitter ind_kshitij",
    "SaaS Developer",
    "Product Engineer",
    "Frontend Architect",
    "Full Stack JavaScript Engineer",
    "API Engineer",
    "Cloud Native Developer",
    "Performance Engineer",
    "UI Engineer",
    "UX Focused Developer",
    "AI SaaS Developer",
    "Frontend Performance Optimization",
    "Backend API Optimization",
    "Database Design Developer",
    "Scalable Architecture Developer",
    "Microfrontend Developer",
    "Web Performance Engineer",
    "Cloud Platform Engineer",
    "V8 JavaScript Developer",
    "Next.js Enterprise Developer",
    "Full Stack JavaScript Developer",
    "Custom Dashboard Developer",
    "Admin Panel Developer",
    "CMS Developer",
    "Enterprise Software Developer",
    "Automation Developer",
    "Digital Product Developer",
    "SaaS Platform Builder",
    "End-to-End Developer",
    "Web Application Engineer",
    "Secure Coding Developer",
    "Application Security Developer",
    "Identity Authentication Engineer",
    "OAuth2 Developer",
    "JWT Token Developer",
    "Full Stack Web Engineer",
    "API Integration Developer",
    "Database Performance Developer",
    "System Design Developer",
    "Event-Driven Architecture Developer",
    "Realtime Applications Developer",
    "WebSockets Developer",
    "GraphQL Developer",
    "tRPC Developer",
    "Server Actions Developer",
    "React Server Components Developer",
    "UI Component Builder",
    "Design Systems Developer",
    "Reusable Component Developer",
    "Full Stack Portfolio Developer",
    "High Performance UI Developer",
    "SEO Web Developer",
    "On-Page SEO Developer",
    "JavaScript Performance Expert",
    "Next.js SEO Developer",
    "UI Animation Developer",
    "Framer Motion Expert",
    "Responsive UI Engineer",
    "Web Accessibility Developer",
    "A11y Developer",
    "WCAG Developer",
    "Core Web Vitals Developer",
    "Performance Metrics Developer",
    "Progressive Web App Developer",
    "PWA Developer",
    "Offline First Developer",
    "Caching Optimization Developer",
    "Redis Developer",
    "Cloud Functions Developer",
    "Serverless Functions Developer",
    "Lambda Functions Developer",
    "RESTful API Expert",
    "OpenAPI Developer",
    "Swagger API Developer",
    "API Documentation Developer",
    "Full Stack Problem Solver",
    "Developer India Portfolio",
    "Tech Portfolio India",
    "Software Portfolio India",
    "Coding Projects Portfolio",
    "Interview Preparation Developer",
    "AI Interview Tools Developer",
    "Developer Productivity Tools",
    "Code Quality Developer",
    "Scalable API Developer",
    "Real-Time Data Developer",
    "Streaming Applications Developer",
    "Event Queue Developer",
    "AI Chat Interface Developer",
    "Embedded AI Developer",
    "LLM Prompt Engineer",
    "Prompt Engineering Developer",
    "AI Workflow Developer",
    "Backend Logic Developer",
    "Frontend Logic Developer",
    "High Traffic Application Developer",
    "Enterprise Web Developer",
    "Full Stack Automation Engineer",
    "React Hooks Developer",
    "Custom Hooks Developer",
    "Next.js API Routes Developer",
    "AI-Powered Web Developer",
    "Modern JavaScript Engineer",
    "Tech Influencer Portfolio",
    "Kshitij",
    "Kshittij",
    "Kshitej",
    "Kshitej Singh",
    "Kshtij",
    "Ksitij",
    "Ksitiej",
    "Kshitij S",
    "Kshitij07",
    "Kshitijsingh07",
    "1kshitij",
    "kkkshitij",
    "ind_kshitij",
    "indkshitij",
    "itskshitij",
    "officialkshitij",
    "kshitij.dev",
    "kshitij.tech",
    "kshitij.codes",
    "kshitijsingh.dev",
    "kshitijsingh.tech",
    "shitij",
    "shitij Singh",
    "shitij07",
    "shittij",
    "shitij developer",
    "shitij full stack",
    "shitijsingh",
    "JavaScript Engineer India",
    "TypeScript Engineer India",
    "React JS Specialist",
    "Next JS Specialist",
    "Advanced MERN Developer",
    "Next.js App Router Developer",
    "Static Site Developer",
    "Hybrid Rendering Developer",
    "ISR Optimization",
    "Next.js 14 Developer",
    "Server Components Expert",
    "Client Components Developer",
    "AI Chatbot Engineer",
    "AI Product Developer",
    "AI SaaS Platform Engineer",
    "ML Web Integration",
    "AI Frontend Specialist",
    "AI Backend Specialist",
    "AI Engineering Portfolio",
    "Web3 Ready Developer",
    "JWT Security Expert",
    "OAuth Security Expert",
    "Type Safety Developer",
    "Zod Validation Developer",
    "Backend Reliability Engineer",
    "Database Optimization Expert",
    "Indexing Optimization Developer",
    "Schema Design Expert",
    "Clean Architecture Developer",
    "Domain Driven Developer",
    "API Scalability Engineer",
    "System Architecture Designer",
    "Software Architect India",
    "Cloud Engineering Portfolio",
    "DevOps Friendly Developer",
    "CICD Specialist",
    "Pipeline Automation Developer",
    "SaaS Dashboard Engineer",
    "Custom CMS Developer",
    "Ecommerce Web Developer",
    "Digital Product Builder",
    "Real-Time Systems Developer",
    "Stock Market App Developer",
    "Analytics Dashboard Developer",
    "Data Visualization Developer",
    "Charts Developer",
    "High Scale App Developer",
    "Production Ready Developer",
    "Enterprise UI Developer",
    "Reusable UI Components Engineer",
    "Component Library Developer",
    "UI Performance Tuner",
    "DOM Optimization Developer",
    "SSR Optimization Expert",
    "SEO Performance Developer",
    "Search Engine Friendly Developer",
    "Accessibility First Developer",
    "WCAG Accessibility Specialist",
    "Screen Reader Friendly Developer",
    "Keyboard Navigation Developer",
    "Frontend Testing Developer",
    "Unit Testing Developer",
    "Integration Testing Developer",
    "Jest Developer",
    "Vitest Developer",
    "Storybook Developer",
    "Design Systems Specialist",
    "UI Engineering Specialist",
    "UX Interaction Developer",
    "Motion UI Specialist",
    "Animation Developer",
    "Complex UI Developer",
    "Interactive UI Developer",
    "Digital Designer Developer",
    "UI Framework Developer",
    "Cross Browser Developer",
    "Cross Platform Developer",
    "Full Stack Web Apps",
    "API Gateway Developer",
    "Reverse Proxy Developer",
    "Nginx Developer",
    "Server Management Developer",
    "Full Stack Cloud Engineer",
    "Vercel Optimized Developer",
    "Cloudflare Developer",
    "Edge Functions Developer",
    "AI Agents Developer",
    "Workflow Automation AI",
    "Fine Tuning Engineer",
    "Vector Database Developer",
    "Pinecone Developer",
    "Weaviate Developer",
    "RAG Developer",
    "Prompt Engineering Specialist",
    "AI Integrations Engineer",
    "Realtime Chat Developer",
    "Messaging Application Developer",
    "Collaborative Apps Developer",
    "Admin Dashboard Developer",
    "User Management Developer",
    "Authentication Specialist",
    "Multi Tenant Developer",
    "Subscription SaaS Developer",
    "Stripe Integration Developer",
    "Payments Web Developer",
    "Webhook Developer",
    "Third Party API Integrator",
    "Cloud Monitoring Developer",
    "Error Tracking Developer",
    "Logging System Developer",
    "Analytics Integrations Developer",
    "Google Analytics Developer",
    "Heatmap Developer",
    "Product Analytics Developer",
    "Profiling Web Apps",
    "Memory Optimization Developer",
    "Execution Time Optimizer",
    "API Response Optimizer",
    "Caching Specialist",
    "Browser Cache Expert",
    "Backend Cache Expert",
    "Full Stack Debugging Developer",
    "Bug Fixing Expert",
    "Production Debugging Developer",
    "Scalable UI Systems",
    "Blueprint Driven Developer",
    "UX Strategy Developer",
    "Product Thinking Developer",
    "Design Thinking Engineer",
    "Feature Development Expert",
    "Complex Feature Developer",
    "SaaS MVP Developer",
    "Prototype to Production Developer",
    "Full Lifecycle Developer",
    "High end UI Developer",
    "Minimalist UI Developer",
    "AI Portfolio Developer",
    "JavaScript Algorithms Developer",
    "DSA Portfolio Developer",
    "Coding Portfolio India",
    "Next.js Portfolio India",
    "Frontend Leadership Skills",
    "Tech Leadership Developer",
    "Team Collaboration Developer",
    "Cross Functional Developer",
    "High Growth Startup Developer",
    "Startup Mindset Developer",
    "Freelance Full Stack Developer",
    "Contract Web Developer",
    "Remote Web Developer",
    "Global Developer Portfolio",
    "Professional JavaScript Engineer",
    "Cutting Edge Web Developer",
    "Modern UI Developer",
    "Backend Logic Specialist",
    "Architecture Patterns Developer",
    "SOLID Principles Developer",
    "KISS Principle Developer",
    "DRY Principle Developer",
    "Reusable Logic Engineer",
    "Advanced Web Engineering",
    "Hybrid App Developer",
    "Custom Hooks Engineer",
    "Reusable API Client Developer",
    "Software Craftsman Developer",
    "Pixel Perfect UI Developer",
    "Browser API Specialist",
    "Web Worker Developer",
    "Service Worker Developer",
    "Background Sync Developer",
    "Offline App Developer",
    "IndexedDB Developer",
    "Form Engineering Specialist",
    "State Machines Developer",
    "XState Developer",
    "tRPC API Specialist",
    "GraphQL Client Developer",
    "Apollo Developer",
    "Client Side Caching Developer",
    "AI Business Developer",
    "AI Startup Developer",
    "SaaS Automation Tools",
    "Engineering Portfolio India",
    "Coding Journey Developer",
    "CS Fundamentals Developer",
    "Algorithms Developer",
    "System Design Portfolio",
    "JavaScript Mastery Developer",
    "TypeScript Mastery Developer",
    "React Masterclass Developer",
    "Next.js Masterclass Developer",
    "Cloud Mastery Developer",
    "Tech Community Member",
    "Tech Blogger Developer",
    "Mentor Developer",
    "AI Mentor Developer",
    "SaaS Maker",
    "Web App Maker",
    "Creative Developer",
  ],
  authors: [{ name: "Kshitij Singh", url: "https://kshitijsingh.vercel.app/" }],
  creator: "Kshitij Singh",

  // 🔗 Social Links (via metadata metadataBase + alternates)
  metadataBase: new URL("https://kshitijsingh.vercel.app"),

  alternates: {
    canonical: "https://kshitijsingh.vercel.app",
  },

  openGraph: {
    title: "Kshitij Singh — Full-Stack Developer",
    description:
      "Explore the portfolio of Kshitij Singh: Full-Stack Developer experienced in Next.js, TypeScript, MERN stack, and AI-based applications.",
    url: "https://kshitijsingh.vercel.app",
    siteName: "Kshitij Singh Portfolio",
    type: "website",
    // images: [
    //   {
    //     url: "/og-image.png", // optional if you add OG image
    //     width: 1200,
    //     height: 630,
    //     alt: "Kshitij Singh Portfolio Preview",
    //   },
    // ],
  },

  // Your social + dev links
  other: {
    linktree: "https://linktr.ee/1kshitij",
    email: "ind.kshitijsingh@gmail.com",
    linkedin: "https://www.linkedin.com/in/kshitijsingh07/",
    github: "https://github.com/indkshitij",
    leetcode: "https://leetcode.com/u/1kshitij/",
    instagram: "https://www.instagram.com/kkkshitij/",
    twitter: "https://x.com/ind_kshitij",
    portfolio: "https://kshitijsingh.vercel.app/",
  },

  icons: {
    icon: "/KS.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SpeedInsights />
        <StoreProveider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster position="top-center" />
            {children}
          </ThemeProvider>
        </StoreProveider>
      </body>
    </html>
  );
}
